function [low up variance]=kci(boots,quantiles)
%
% License: RipleyGUI is distributed free under the conditions that
% (1) it shall not be incorporated in software that is subsequently sold; 
% (2) the authorship of the software shall be acknowledged in any publication that uses results generated by the software; 
% (3) this notice shall remain in place in each source file. 

% default interval is 95%
if nargin<2, 
    quantiles=[0.025 0.975]; 
end

[bootnum tlength]=size(boots);
for j=1:tlength
    temp=sort(boots(:,j));
    low(j)=temp(round(bootnum*quantiles(1)));
    up(j)=temp(round(bootnum*quantiles(2)));
end
variance=var(boots);
