function out=resid(k,n,K_average)
% out=resid(k,n)
% k - a matrix with all K-value arrays in a group
% n - number of events for each distribution in the group
% K_average - the weighted average
%
% License: RipleyGUI is distributed free under the conditions that
% (1) it shall not be incorporated in software that is subsequently sold; 
% (2) the authorship of the software shall be acknowledged in any publication that uses results generated by the software; 
% (3) this notice shall remain in place in each source file. 
for j=1:numel(n)
    out(j,:)=sqrt(n(j))*(k(j,:)-K_average);
end