function out = w_distance(pointA, pointB)
% calculate the distance between point A and B
%
% License: RipleyGUI is distributed free under the conditions that
% (1) it shall not be incorporated in software that is subsequently sold; 
% (2) the authorship of the software shall be acknowledged in any publication that uses results generated by the software; 
% (3) this notice shall remain in place in each source file. 
ax = pointA(1);
ay = pointA(2);
az = pointA(3);
bx = pointB(1);
by = pointB(2);
bz = pointB(3);

out = sqrt( (ax-bx)^2 + (ay-by)^2 + (az-bz)^2 );