function out=wa(K,n) 
% weighted average
% out=wa(K,n)
%
% License: RipleyGUI is distributed free under the conditions that
% (1) it shall not be incorporated in software that is subsequently sold; 
% (2) the authorship of the software shall be acknowledged in any publication that uses results generated by the software; 
% (3) this notice shall remain in place in each source file. 
out=((K'*n)/sum(n))';
end